/**
 * Viewer Token Service
 * Hito 3.1 + 3.2: Unified viewer token with Redis caching
 *
 * Features:
 * - Single source of truth for viewer tokens (2-legged)
 * - Redis cache with 60s safety margin
 * - Concurrency lock to prevent token storm
 * - No session required (internal credentials)
 */

import { redis } from "../../lib/redis";
import { apsAuthService } from "../aps/auth.service";
import { CONSTANTS } from "../../config/constants";
import { logger } from "../../lib/logger";

const REDIS_KEY_TOKEN = "viewer:token:internal:v1";
const REDIS_KEY_LOCK = "viewer:token:lock:v1";
const LOCK_TTL_SECONDS = CONSTANTS.VIEWER_TOKEN.LOCK_TTL_SECONDS;
const SAFETY_MARGIN_SECONDS = CONSTANTS.VIEWER_TOKEN.SAFETY_MARGIN_SECONDS;
const LOCK_RETRY_MS = 200;
const MAX_LOCK_RETRIES = 25; // 5 seconds max wait

interface CachedToken {
  access_token: string;
  token_type: string;
  expires_at_epoch_ms: number;
  expires_in_original: number;
}

export interface ViewerTokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
  expires_at: number; // epoch ms
  requestId?: string;
}

export class ViewerTokenService {
  /**
   * Get viewer token (2-legged internal)
   * Uses cache if available and valid
   */
  async getViewerToken(requestId?: string): Promise<ViewerTokenResponse> {
    const startTime = Date.now();

    // 1. Try cache first
    const cached = await this.getCachedToken();

    if (cached) {
      const timeUntilExpiry = cached.expires_at_epoch_ms - Date.now();
      const tokenAgeSec = Math.floor(
        (Date.now() -
          (cached.expires_at_epoch_ms - cached.expires_in_original * 1000)) /
          1000,
      );

      // Check if still valid (not within safety margin)
      if (timeUntilExpiry > SAFETY_MARGIN_SECONDS * 1000) {
        logger.debug("[VIEWER_TOKEN] Cache hit", {
          cacheHit: true,
          tokenAgeSec,
          timeUntilExpirySec: Math.floor(timeUntilExpiry / 1000),
          requestId,
        });

        return {
          access_token: cached.access_token,
          token_type: cached.token_type,
          expires_in: Math.floor(timeUntilExpiry / 1000),
          expires_at: cached.expires_at_epoch_ms,
          requestId,
        };
      }

      logger.debug("[VIEWER_TOKEN] Token expiring soon, will refresh", {
        timeUntilExpirySec: Math.floor(timeUntilExpiry / 1000),
        requestId,
      });
    }

    // 2. Cache miss or expiring - need new token
    logger.debug("[VIEWER_TOKEN] Cache miss", {
      cacheHit: false,
      requestId,
    });

    // 3. Try to acquire lock
    const lockAcquired = await this.acquireLock();

    if (!lockAcquired) {
      // Another request is generating token, wait and retry
      logger.debug("[VIEWER_TOKEN] Lock held, waiting for token generation", {
        requestId,
      });

      for (let i = 0; i < MAX_LOCK_RETRIES; i++) {
        await this.sleep(LOCK_RETRY_MS);

        const newCached = await this.getCachedToken();
        if (
          newCached &&
          newCached.expires_at_epoch_ms - Date.now() >
            SAFETY_MARGIN_SECONDS * 1000
        ) {
          logger.debug("[VIEWER_TOKEN] Token generated by concurrent request", {
            retries: i + 1,
            requestId,
          });

          return {
            access_token: newCached.access_token,
            token_type: newCached.token_type,
            expires_in: Math.floor(
              (newCached.expires_at_epoch_ms - Date.now()) / 1000,
            ),
            expires_at: newCached.expires_at_epoch_ms,
            requestId,
          };
        }
      }

      // Lock released but no valid token
      throw new Error("VIEWER_TOKEN_BUSY");
    }

    // 4. We have the lock, generate new token
    try {
      logger.debug("[VIEWER_TOKEN] Generating new token from APS", {
        requestId,
      });

      const tokenData = await this.generateNewToken();

      // 5. Cache the new token
      await this.cacheToken(tokenData);

      const duration = Date.now() - startTime;
      logger.info("[VIEWER_TOKEN] Token generated and cached", {
        durationMs: duration,
        expiresIn: tokenData.expires_in_original,
        requestId,
      });

      return {
        access_token: tokenData.access_token,
        token_type: tokenData.token_type,
        expires_in: tokenData.expires_in_original,
        expires_at: tokenData.expires_at_epoch_ms,
        requestId,
      };
    } finally {
      // Always release lock
      await this.releaseLock();
    }
  }

  /**
   * Generate new token from APS (2-legged internal)
   */
  private async generateNewToken(): Promise<CachedToken> {
    const credentials = (await apsAuthService.getViewerToken()) as {
      access_token: string;
      token_type: string;
      expires_in: number;
    };

    const expiresAt = Date.now() + credentials.expires_in * 1000;

    return {
      access_token: credentials.access_token,
      token_type: credentials.token_type || "Bearer",
      expires_at_epoch_ms: expiresAt,
      expires_in_original: credentials.expires_in,
    };
  }

  /**
   * Get cached token from Redis
   */
  private async getCachedToken(): Promise<CachedToken | null> {
    try {
      const cached = await redis.get(REDIS_KEY_TOKEN);
      if (!cached) return null;

      const parsed: CachedToken = JSON.parse(cached);
      return parsed;
    } catch (error) {
      logger.error("[VIEWER_TOKEN] Cache read error", {
        error: error instanceof Error ? error.message : String(error),
      });
      return null;
    }
  }

  /**
   * Cache token in Redis with TTL
   */
  private async cacheToken(token: CachedToken): Promise<void> {
    try {
      const ttl = token.expires_in_original - SAFETY_MARGIN_SECONDS;

      await redis.setex(
        REDIS_KEY_TOKEN,
        ttl > 0 ? ttl : token.expires_in_original,
        JSON.stringify(token),
      );

      logger.debug("[VIEWER_TOKEN] Token cached", {
        ttl,
        expiresAt: new Date(token.expires_at_epoch_ms).toISOString(),
      });
    } catch (error) {
      logger.error("[VIEWER_TOKEN] Cache write error", {
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  /**
   * Acquire lock for token generation
   */
  private async acquireLock(): Promise<boolean> {
    try {
      const result = await redis.set(
        REDIS_KEY_LOCK,
        "1",
        "EX",
        LOCK_TTL_SECONDS,
        "NX",
      );
      return result === "OK";
    } catch (error) {
      logger.error("[VIEWER_TOKEN] Lock acquire error", {
        error: error instanceof Error ? error.message : String(error),
      });
      return false;
    }
  }

  /**
   * Release lock
   */
  private async releaseLock(): Promise<void> {
    try {
      await redis.del(REDIS_KEY_LOCK);
    } catch (error) {
      logger.error("[VIEWER_TOKEN] Lock release error", {
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  /**
   * Sleep helper
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}

// Conditional: use mock when APS_MOCK=true
import { env } from "../../config/env";
import { MockViewerTokenService } from "../../mocks/aps-mock";

export const viewerTokenService: ViewerTokenService = env.APS_MOCK
  ? (new MockViewerTokenService() as unknown as ViewerTokenService)
  : new ViewerTokenService();
