"use client"

/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useRef, useState } from "react"
import axios from "axios"
import { isMockUrn } from "@/lib/utils"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { AlertCircle } from "lucide-react"
import { useUser } from "@/context/UserContext"
import { showError } from "@/lib/error-handler"

interface ViewerProps {
    urn: string
    token?: string
}

declare global {
    interface Window {
        Autodesk: any
    }
}

export default function Viewer({ urn, token: providedToken }: ViewerProps) {
    const containerRef = useRef<HTMLDivElement>(null)
    const [viewer, setViewer] = useState<any>(null)
    const { user } = useUser()
    const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080'

    // Professional handling of Mock/Simulation Data
    // The Autodesk Viewer requires a valid URN generated by the Model Derivative API.
    // Local mock files do not have this geometry data, so we render a simulation state
    // to prevent the viewer from throwing 404 errors.
    if (isMockUrn(urn)) {
        return (
            <div className="w-full h-full flex items-center justify-center bg-muted/20 p-6">
                <Card className="max-w-md w-full border-dashed">
                    <CardHeader className="text-center pb-2">
                        <div className="mx-auto bg-primary/10 p-3 rounded-full w-fit mb-4">
                            <AlertCircle className="h-6 w-6 text-primary" />
                        </div>
                        <CardTitle>Simulation Mode (Test File)</CardTitle>
                        <CardDescription>
                            This is a generated test file with no visual data.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="text-center text-sm text-muted-foreground space-y-4">
                        <p>
                            To see the real 2D/3D Viewer, please <strong>upload your real .DWG file</strong> using the "Upload File" button in the dashboard.
                        </p>
                        <div className="bg-muted p-3 rounded text-xs font-mono">
                            URN: {urn}
                        </div>
                    </CardContent>
                </Card>
            </div>
        )
    }

    useEffect(() => {
        const loadViewer = async () => {
            if (!window.Autodesk) {
                // Load APS Viewer scripts dynamically if not present
                const link = document.createElement("link")
                link.rel = "stylesheet"
                link.href = "https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/style.min.css"
                document.head.appendChild(link)

                const script = document.createElement("script")
                script.src = "https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/viewer3D.min.js"
                script.onload = initializeViewer
                document.body.appendChild(script)
            } else {
                initializeViewer()
            }
        }

        const loadModel = (viewerInstance: any, modelUrn: string) => {
            const documentId = "urn:" + modelUrn
            window.Autodesk.Viewing.Document.load(
                documentId,
                (doc: any) => {
                    const defaultModel = doc.getRoot().getDefaultGeometry()
                    viewerInstance.loadDocumentNode(doc, defaultModel)
                },
                (errorCode: any, errorMsg: any) => {
                    // console.error("Load Error:", errorCode, errorMsg)
                    showError(new Error(`Viewer Load Error: ${errorCode}`), user?.role, "Model Loading Failed")
                }
            )
        }

        const initializeViewer = async () => {
            try {
                let token = providedToken;
                
                if (!token) {
                    const response = await axios.get(`${API_URL}/api/auth/token`)
                    token = response.data.access_token
                }

                const options = {
                    env: "AutodeskProduction",
                    accessToken: token,
                    isAEC: true,
                }

                window.Autodesk.Viewing.Initializer(options, () => {
                    if (containerRef.current) {
                        const newViewer = new window.Autodesk.Viewing.GuiViewer3D(containerRef.current)
                        newViewer.start()
                        setViewer(newViewer)
                        loadModel(newViewer, urn)
                    }
                })
            } catch (error) {
                // console.error("Failed to initialize viewer:", error)
                showError(error, user?.role, "Viewer Initialization Failed")
            }
        }

        loadViewer()

        return () => {
            if (viewer) {
                viewer.finish()
            }
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [urn, user?.role])

    return <div ref={containerRef} className="w-full h-full relative" />
}
